---
# tasks file for sample-apache
- name: installing httpd, mod_ssl, php
  yum:
    name:
      - httpd
      - mod_ssl
      - php
    state: present
- name: make sure apache service running and enabled
  service:
    name: httpd 
    state: started
    enabled: yes
- name: firewall http
  firewalld:
    permanent: yes
    immediate: yes
    zone: public
#   service: http
    port: 80/tcp
    state: enabled
- name: firewall https
  firewalld:
    permanent: yes
    immediate: yes
    zone: public
#   service: https
    port: 443/tcp
    state: enabled
- name: 
  template:
    src: index.html.j2
    dest: /var/www/html/index.html
  notify: RESTART_HTTPD
