---
- name: Work with Ansible Facts Task15
  hosts: database
  gather_facts: no
  become: yes
  tasks:
#    - name: create ansible directory
#      file:
#        path: /etc/ansible
#        state: directory
    - name: create custom.fact directory
      file:
        path: /etc/ansible/facts.d
        state: directory
    - name: insert custom.fact file
      copy:
        src: files/custom.fact
        dest: /etc/ansible/facts.d/custom.fact
    - name: retrieve facts
      setup:
    - name: fail when not retrieved
      debug:
        msg: "custom facts is not retrieved"
      when: ansible_local.custom.sample_exam is not defined
