---
- name: Use Conditionals to Control Play Execution Task13
  hosts: all
  become: yes
  ignore_errors: yes
  tasks:
    - name: temp
      debug:
        msg: "{{ ansible_memtotal_mb }}"
    - name: update vm.swapping to 10 when ram size > 2048mb
      sysctl:
        name: vm.swappiness
        value: '10'
        state: present
        reload: yes
      when: ansible_memtotal_mb > 2048
    - name: print fail if < 2048mb
      fail:
#     debug:
        msg: "Server memory less than 2048MB"
      when: ansible_memtotal_mb < 2048    

